### ISSUE TITLE
Please add SHA256 for downloads

### ISSUE THREAD

**Issue by technosophos** [vmware-labs/webassembly-language-runtimes#20]
On the releases page, would you be able to add SHA256 digests for each of the binaries?

For Spin, we use the digest to verify that when we fetch a binary from GitHub at startup time, it has not been maliciously altered. Here's and example for one of our other projects:

```toml
[[component]]
source = { url = "https://github.com/fermyon/spin-redirect/releases/download/v0.0.1/redirect.wasm", digest = "sha256:d57c3d91e9b62a6b628516c6d11daf6681e1ca2355251a3672074cddefd7f391" }
id = "Redirect"
environment = { DESTINATION = "/index.php" }
[component.trigger]
route = "/"
executor = { type = "wagi" }
```

Note that `redirect.wasm` is fetched from a repository, and then the `digest = ` field is used to verify that the data was not altered.

Here's what `php-wasm` looks like in my current Spin PHP app:

```toml
[[component]]
# Latest PHP-Wasm
source = { url = "https://github.com/vmware-labs/webassembly-language-runtimes/releases/download/php%2F7.4.32%2B20221124-2159d1c/php-cgi-7.4.32.speed-optimized.wasm", digest = "sha256:511720698dee56134ed8a08a87131d33c3ea8a64b6726cd6710d624bca4ceb6c" }
id = "PHP"
files = [ { source = "./src", destination = "/" } ]
[component.trigger]
# Make sure the executor is wagi
executor = { type = "wagi"}
# This means PHP will be used for all requests.
route = "/..."
```

To generate the `digest` there, I first downloaded the `php-cgi-7.4.32.speed-optimized.wasm` then ran `shasum -a 256 php-cgi-7.4.32.speed-optimized.wasm`. That works, but is a little inconvenient and still assumes that the version I fetched hadn't been compromised. 

I wouldn't say that Helm is exactly the gold standard for how this should be done, but here's how we do them for that project: https://github.com/helm/helm/releases

Thanks! I am having a great time applying my old PHP skills to this new technology stack!
